title: FSS
description: FSS plugin
show_downloads: true
google_analytics: true
baseurl: "https://github.com/annapasca/FSS/"
source: docs
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
    authors:
        output: true
