title: FSS
description: FSS plugin
show_downloads: true
google_analytics: true
remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
    authors:
        output: true
